### ISSUE TITLE
The pre-trained model on the task of code search

### ISSUE THREAD

**Issue by skye95git** [Jun-jie-Huang/CoCLR#1]
In the `Model Checkpoint` section, there is the link of the checkpoint with best code question answering results. Can you share your pre-trained model on the task of code search?

**Comment by Jun-jie-Huang** [comment]
Do you mean the checkpoint trained on CodeSearchNet or trained on CoSQA?

**Comment by skye95git** [comment]
> Do you mean the checkpoint trained on CodeSearchNet or trained on CoSQA?

Yes, the checkpoint with best code search results.

**Comment by Jun-jie-Huang** [comment]
OK, I will upload the checkpoint asap.

**Comment by skye95git** [comment]
> OK, I will upload the checkpoint asap.

Thanks. The work is cool.

**Comment by skye95git** [comment]
> Hi, the checkpoint on the task of code search has been uploaded. Please refer to [this](https://github.com/Jun-jie-Huang/CoCLR#model-checkpoint).

Thanks! Was this checkpoint trained on CoSQA?

**Comment by Jun-jie-Huang** [comment]
> > Hi, the checkpoint on the task of code search has been uploaded. Please refer to [this](https://github.com/Jun-jie-Huang/CoCLR#model-checkpoint).
> 
> Thanks! Was this checkpoint trained on CoSQA?

Yes

**Comment by skye95git** [comment]
> Hi, the checkpoint on the task of code search has been uploaded. Please refer to [this](https://github.com/Jun-jie-Huang/CoCLR#model-checkpoint).

Hi, I make dir `./model/codesearchnet-checkpoint` and save the checkpoint trained on CodeSearchNet in it. 
<img width="655" alt="捕获" src="https://user-images.githubusercontent.com/41561936/131773757-bf261911-1907-4eb3-89c3-147fd59de57a.PNG">

Then I make dir `./model/search_codebert_switch`. 
<img width="441" alt="捕获" src="https://user-images.githubusercontent.com/41561936/131773830-c0a43c02-64e0-4c47-b730-0fdee1d88116.PNG">

When I run the [step3](https://github.com/Jun-jie-Huang/CoCLR#step-3-training-and-evaluating) in CoCLR on Code Search section, there is an error:
![image](https://user-images.githubusercontent.com/41561936/131772906-33eeb40f-f347-4d07-932e-73699c960ba6.png)

I search the error on the internet:
<img width="533" alt="捕获" src="https://user-images.githubusercontent.com/41561936/131773049-cc721548-a70c-4448-a557-af9ac24fc699.PNG">

**But I don't konw which dimensionality should be changed. What should I do? Did I do something wrong?**

I hava another question: I download the checkpoint with best code search results you provided and move then to  `./model/`:
<img width="1025" alt="捕获" src="https://user-images.githubusercontent.com/41561936/131774772-6d4b279c-f6f6-4a00-9000-cf8fd76488c9.PNG">

**Can this checkpoint be used directly for evaluation? Why is there an error when I use it?**
<img width="1095" alt="捕获" src="https://user-images.githubusercontent.com/41561936/131774437-f5384b64-1358-4876-be52-6ff5a01e5c60.PNG">

**Isn't the checkpoint stored in the `./model/`?**

**Comment by Jun-jie-Huang** [comment]
> > Hi, the checkpoint on the task of code search has been uploaded. Please refer to [this](https://github.com/Jun-jie-Huang/CoCLR#model-checkpoint).
> 
> Hi, I make dir `./model/codesearchnet-checkpoint` and save the checkpoint trained on CodeSearchNet in it.
> <img alt="捕获" width="655" src="https://user-images.githubusercontent.com/41561936/131773757-bf261911-1907-4eb3-89c3-147fd59de57a.PNG">
> 
> Then I make dir `./model/search_codebert_switch`.
> <img alt="捕获" width="441" src="https://user-images.githubusercontent.com/41561936/131773830-c0a43c02-64e0-4c47-b730-0fdee1d88116.PNG">
> 
> When I run the [step3](https://github.com/Jun-jie-Huang/CoCLR#step-3-training-and-evaluating) in CoCLR on Code Search section, there is an error:
> ![image](https://user-images.githubusercontent.com/41561936/131772906-33eeb40f-f347-4d07-932e-73699c960ba6.png)
> 
> I search the error on the internet:
> <img alt="捕获" width="533" src="https://user-images.githubusercontent.com/41561936/131773049-cc721548-a70c-4448-a557-af9ac24fc699.PNG">
> 
> **But I don't konw which dimensionality should be changed. What should I do? Did I do something wrong?**
> 
> I hava another question: I download the checkpoint with best code search results you provided and move then to `./model/`:
> <img alt="捕获" width="1025" src="https://user-images.githubusercontent.com/41561936/131774772-6d4b279c-f6f6-4a00-9000-cf8fd76488c9.PNG">
> 
> **Can this checkpoint be used directly for evaluation? Why is there an error when I use it?**
> <img alt="捕获" width="1095" src="https://user-images.githubusercontent.com/41561936/131774437-f5384b64-1358-4876-be52-6ff5a01e5c60.PNG">
> 
> **Isn't the checkpoint stored in the `./model/`?**



Question 2: I think made a mistake that I uploaded a checkpoint for QA. I have updated the link now with the right code search model.

**Comment by skye95git** [comment]
> > > Hi, the checkpoint on the task of code search has been uploaded. Please refer to [this](https://github.com/Jun-jie-Huang/CoCLR#model-checkpoint).
> > 
> > 
> > Hi, I make dir `./model/codesearchnet-checkpoint` and save the checkpoint trained on CodeSearchNet in it.
> > <img alt="捕获" width="655" src="https://user-images.githubusercontent.com/41561936/131773757-bf261911-1907-4eb3-89c3-147fd59de57a.PNG">
> > Then I make dir `./model/search_codebert_switch`.
> > <img alt="捕获" width="441" src="https://user-images.githubusercontent.com/41561936/131773830-c0a43c02-64e0-4c47-b730-0fdee1d88116.PNG">
> > When I run the [step3](https://github.com/Jun-jie-Huang/CoCLR#step-3-training-and-evaluating) in CoCLR on Code Search section, there is an error:
> > ![image](https://user-images.githubusercontent.com/41561936/131772906-33eeb40f-f347-4d07-932e-73699c960ba6.png)
> > I search the error on the internet:
> > <img alt="捕获" width="533" src="https://user-images.githubusercontent.com/41561936/131773049-cc721548-a70c-4448-a557-af9ac24fc699.PNG">
> > **But I don't konw which dimensionality should be changed. What should I do? Did I do something wrong?**
> > I hava another question: I download the checkpoint with best code search results you provided and move then to `./model/`:
> > <img alt="捕获" width="1025" src="https://user-images.githubusercontent.com/41561936/131774772-6d4b279c-f6f6-4a00-9000-cf8fd76488c9.PNG">
> > **Can this checkpoint be used directly for evaluation? Why is there an error when I use it?**
> > <img alt="捕获" width="1095" src="https://user-images.githubusercontent.com/41561936/131774437-f5384b64-1358-4876-be52-6ff5a01e5c60.PNG">
> > **Isn't the checkpoint stored in the `./model/`?**
> 
> Question 2: I think made a mistake that I uploaded a checkpoint for QA. I have updated the link now with the right code search model. Sorry about that..

Thanks for your reply! Are downloaded file `checkpoint-test-mrr` stored in the `./model` folder or `./model/search_codebert_switch` folder?

**Comment by skye95git** [comment]
> > > Hi, the checkpoint on the task of code search has been uploaded. Please refer to [this](https://github.com/Jun-jie-Huang/CoCLR#model-checkpoint).
> > 
> > 
> > Hi, I make dir `./model/codesearchnet-checkpoint` and save the checkpoint trained on CodeSearchNet in it.
> > <img alt="捕获" width="655" src="https://user-images.githubusercontent.com/41561936/131773757-bf261911-1907-4eb3-89c3-147fd59de57a.PNG">
> > Then I make dir `./model/search_codebert_switch`.
> > <img alt="捕获" width="441" src="https://user-images.githubusercontent.com/41561936/131773830-c0a43c02-64e0-4c47-b730-0fdee1d88116.PNG">
> > When I run the [step3](https://github.com/Jun-jie-Huang/CoCLR#step-3-training-and-evaluating) in CoCLR on Code Search section, there is an error:
> > ![image](https://user-images.githubusercontent.com/41561936/131772906-33eeb40f-f347-4d07-932e-73699c960ba6.png)
> > I search the error on the internet:
> > <img alt="捕获" width="533" src="https://user-images.githubusercontent.com/41561936/131773049-cc721548-a70c-4448-a557-af9ac24fc699.PNG">
> > **But I don't konw which dimensionality should be changed. What should I do? Did I do something wrong?**
> > I hava another question: I download the checkpoint with best code search results you provided and move then to `./model/`:
> > <img alt="捕获" width="1025" src="https://user-images.githubusercontent.com/41561936/131774772-6d4b279c-f6f6-4a00-9000-cf8fd76488c9.PNG">
> > **Can this checkpoint be used directly for evaluation? Why is there an error when I use it?**
> > <img alt="捕获" width="1095" src="https://user-images.githubusercontent.com/41561936/131774437-f5384b64-1358-4876-be52-6ff5a01e5c60.PNG">
> > **Isn't the checkpoint stored in the `./model/`?**
> 
> Question 2: I think made a mistake that I uploaded a checkpoint for QA. I have updated the link now with the right code search model. Sorry about that..

For the question1, I reloaded cuda and PyTorch and the model can now train properly.

**Comment by skye95git** [comment]
> > > > Hi, the checkpoint on the task of code search has been uploaded. Please refer to [this](https://github.com/Jun-jie-Huang/CoCLR#model-checkpoint).
> > > 
> > > 
> > > Hi, I make dir `./model/codesearchnet-checkpoint` and save the checkpoint trained on CodeSearchNet in it.
> > > <img alt="捕获" width="655" src="https://user-images.githubusercontent.com/41561936/131773757-bf261911-1907-4eb3-89c3-147fd59de57a.PNG">
> > > Then I make dir `./model/search_codebert_switch`.
> > > <img alt="捕获" width="441" src="https://user-images.githubusercontent.com/41561936/131773830-c0a43c02-64e0-4c47-b730-0fdee1d88116.PNG">
> > > When I run the [step3](https://github.com/Jun-jie-Huang/CoCLR#step-3-training-and-evaluating) in CoCLR on Code Search section, there is an error:
> > > ![image](https://user-images.githubusercontent.com/41561936/131772906-33eeb40f-f347-4d07-932e-73699c960ba6.png)
> > > I search the error on the internet:
> > > <img alt="捕获" width="533" src="https://user-images.githubusercontent.com/41561936/131773049-cc721548-a70c-4448-a557-af9ac24fc699.PNG">
> > > **But I don't konw which dimensionality should be changed. What should I do? Did I do something wrong?**
> > > I hava another question: I download the checkpoint with best code search results you provided and move then to `./model/`:
> > > <img alt="捕获" width="1025" src="https://user-images.githubusercontent.com/41561936/131774772-6d4b279c-f6f6-4a00-9000-cf8fd76488c9.PNG">
> > > **Can this checkpoint be used directly for evaluation? Why is there an error when I use it?**
> > > <img alt="捕获" width="1095" src="https://user-images.githubusercontent.com/41561936/131774437-f5384b64-1358-4876-be52-6ff5a01e5c60.PNG">
> > > **Isn't the checkpoint stored in the `./model/`?**
> > 
> > 
> > Question 2: I think made a mistake that I uploaded a checkpoint for QA. I have updated the link now with the right code search model. Sorry about that..
> 
> Thanks for your reply! Are downloaded file `checkpoint-test-mrr` stored in the `./model` folder or `./model/search_codebert_switch` folder?

Thank you. I know the answer.
